version: '3.8'

services:
  youmeos:
    image: xengenie/youmeos:latest
    container_name: youmeos-microverse
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/wp-content:/var/www/html/wp-content
    environment:
      - PORT=80
      - HTTPS_PORT=443
      - WP_DEBUG=false
