services:
  youmeos:
    build:
      context: .
      dockerfile: docker/os/Dockerfile
    image: xengenie/youmeos:latest
    platform: linux/amd64
    container_name: youmeos-microverse
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      - PORT=${PORT:-80}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - OS_HOMEPAGE_MODE=${OS_HOMEPAGE_MODE:-homepage}
      - YOUMEOS_LOAD_MODE=${YOUMEOS_LOAD_MODE:-homepage}
      - WP_DEBUG=false
